### ISSUE TITLE
How to develop with a docker environment 

### ISSUE THREAD

**Issue by luckyjim** [grand-mother/grand#30]

**Comment by luckyjim** [comment]
### Eclipse

install directly in docker is possible with version [4.22](https://www.jetbrains.com/help/pycharm/using-docker-as-a-remote-interpreter.html) dockerfile in course

### Eclispe/che
che IDE has a docker image

https://hub.docker.com/r/eclipse/che

it's possible to do docker in docker , not tested

### PyCharm
PyCharm can use docker as interpreter

https://www.jetbrains.com/help/pycharm/using-docker-as-a-remote-interpreter.html

not tested, your experience ...?

### VScode

VScode can use docker as interpreter

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

not tested, your experience ...?

**Comment by niess** [comment]
Hello Jean-Marc,

concerning this point, I had a similar experience with COMET. This is what I was doing.

1. Use Docker / Singularity as a runtime only, containing Python, its deps and ROOT, but no editor.
2. Store the source of my project locally and work on them using my host editor, git etc.
3. Compile the source using the Docker runtime.

This is not perfect because you need two shells, a Docker one for compiling and another one for managing the source and the editor. But it lets you decouple common tools (ROOT, Python etc.) from more personal ones: editors. Also, I am unsure if you can integrate with an IDE that way? I am using vim without Linting etc.

Maybe the Docker image can be made such that it mimics a Python runtime but containing ROOT as well? Then it might be usable in an IDE? I understand from your comments that it would work with PyCharm and VScode?

**Comment by luckyjim** [comment]
Hello, 

Yes it's possible to have env and dev tools in same docker, I was able to install eclipse in a docker (tested under linux)
see https://hub.docker.com/repository/docker/jcolley/grandlib_eclipse
To do this I configured Eclipse in a container and then created a docker image from this container

https://github.com/grand-mother/grand/blob/dev_docker/env/docker/note_install_eclipse.md

But it is no longer necessary to do it with a "recent" IDE like PyCharm which has the possibility of using a docker image to define its interpreter see [Use the environment defined in a docker](https://hub.docker.com/repository/docker/jcolley/grandlib_dev) on DockerHub.

Here a screenshot of pycharm using jcolley/grandlib_release:demo_master docker image (bottom right "Settings") with python console

![pycharm under docker](https://user-images.githubusercontent.com/6067228/152560542-63aaa783-93fd-47e0-a899-adaf5285e38b.png)
